language: scala
scala:
  - 2.12.8
jdk:
  - openjdk11
sudo: false
services:
  - docker
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
env:
  - DOCKER_COMPOSE_VERSION="1.24.1" TERRAFORM_VERSION="0.11.14"
before_install:
  - sudo service postgresql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip --output terraform.zip
  - unzip terraform.zip -d ${HOME}/bin
  - chmod +x ${HOME}/bin/terraform
  - rm -f terraform.zip
script:
  - terraform fmt -check=true infrastructure
  - docker-compose up -d postgres
  - sleep 5
  - docker-compose run flyway
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll test
deploy:
  on: master
  provider: script
  script: sh ops/build.sh
